=== apache/archiva-sandbox/archiva-jarinfo/archiva-jarinfo-lib/src/main/resources/org/apache/archiva/jarinfo/model/xml/jarinfo-v1_0_0.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://archiva.apache.org/JARINFO/1.0.0" xmlns="http://archiva.apache.org/JARINFO/1.0.0">

    <xs:element name="jar-details" type="JarDetailsType"></xs:element>

    <xs:complexType name="JarDetailsType">
    	<xs:annotation>
    		<xs:documentation>
    			The JarDetails model type
    		</xs:documentation>
    	</xs:annotation>
    	<xs:sequence>
    		<xs:element name="assigned-id" type="AssignedIdType"
    			maxOccurs="1" minOccurs="0">
    		</xs:element>
    		<xs:element name="filename" type="xs:string" minOccurs="1"
    			maxOccurs="1">
    		</xs:element>
    		<xs:element name="timestamp" type="TimestampType"
    			minOccurs="1" maxOccurs="1">
    		</xs:element>
    		<xs:element name="size" type="xs:int" minOccurs="1"
    			maxOccurs="1">
    		</xs:element>
    		<xs:element name="size-uncompressed" type="xs:int"
    			minOccurs="0">
    		</xs:element>
    		<xs:element name="hash" type="HashType"
    			maxOccurs="unbounded" minOccurs="0">
    		</xs:element>
    		<xs:element name="sealed" type="xs:boolean" maxOccurs="1"
    			minOccurs="0">
    		</xs:element>
    		<xs:element name="generator" type="GeneratorType"
    			maxOccurs="1" minOccurs="1">
    		</xs:element>
    		<xs:element name="entries" type="JarEntriesType"
    			maxOccurs="1" minOccurs="0">
    		</xs:element>
    		<xs:element name="bytecode" type="BytecodeType"
    			maxOccurs="1" minOccurs="0">
    		</xs:element>
    		<xs:element name="inspected" type="InspectedIdType" maxOccurs="1" minOccurs="0"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="HashType">
    	<xs:simpleContent>
    		<xs:extension base="xs:string">
    			<xs:attribute name="algorithm" type="hashAlgorithmType" use="required"></xs:attribute>
    		</xs:extension>
    	</xs:simpleContent></xs:complexType>

    <xs:simpleType name="hashAlgorithmType">
    	<xs:restriction base="xs:string">
    		<xs:enumeration value="sha1"></xs:enumeration>
    		<xs:enumeration value="md5"></xs:enumeration>
    	</xs:restriction>
    </xs:simpleType>

    <xs:complexType name="GeneratorType">
    	<xs:sequence>
    		<xs:element name="name" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
    		<xs:element name="version" type="xs:string" maxOccurs="1" minOccurs="0"></xs:element>
    		<xs:element name="timestamp" type="TimestampType" maxOccurs="1" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>



    <xs:simpleType name="TimestampType">
    	<xs:restriction base="xs:string">
    	  <xs:pattern value="[12][0-9][0-9][0-9]-[01][0-9]-[0-3][0-9] [0-2][0-9]:[0-5][0-9]:[0-5][0-9] UTC"/>
    	</xs:restriction>
    </xs:simpleType>

    <xs:complexType name="JarEntriesType">
    	<xs:sequence>
    		<xs:element name="dir" type="DirType" maxOccurs="unbounded" minOccurs="0"></xs:element>
    		<xs:element name="file" type="FileType"
    			maxOccurs="unbounded" minOccurs="0">
    		</xs:element>
    	</xs:sequence>
    	<xs:attribute name="count-dirs" type="xs:int" use="optional"></xs:attribute>
    	<xs:attribute name="count-files" type="xs:int" use="optional"></xs:attribute>
    	<xs:attribute name="count-total" type="xs:int" use="optional"></xs:attribute>
    </xs:complexType>


    <xs:complexType name="DirType">
    	<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
    	<xs:attribute name="timestamp" type="TimestampType" use="required"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="FileType">
    	<xs:sequence>
    		<xs:element name="hash" type="HashType"></xs:element>
    	</xs:sequence>
    	<xs:attribute name="name" type="xs:string"></xs:attribute>
    	<xs:attribute name="timestamp" type="TimestampType"></xs:attribute>
    	<xs:attribute name="size" type="xs:int"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="BytecodeType">
    	<xs:sequence>
    		<xs:element name="hash" type="HashType" maxOccurs="unbounded"
    			minOccurs="0">
    		</xs:element>
    		<xs:element name="jdk" type="xs:string"></xs:element>
    		<xs:element name="debug" type="xs:boolean"></xs:element>
    		<xs:element name="class" maxOccurs="unbounded" minOccurs="1" type="ClassType"></xs:element>
            <xs:element name="package" maxOccurs="unbounded" minOccurs="0" type="xs:string"></xs:element>
    	</xs:sequence>
    	<xs:attribute name="count-classes" type="xs:int"
    		use="optional">
    	</xs:attribute>
    	<xs:attribute name="count-packages" type="xs:int"
    		use="optional">
    	</xs:attribute>
    </xs:complexType>

    <xs:complexType name="ClassType">
    	<xs:sequence>
    		<xs:element name="import" type="xs:string"
    			maxOccurs="unbounded" minOccurs="0">
    		</xs:element>
    		<xs:element name="method" type="xs:string" maxOccurs="unbounded" minOccurs="1"></xs:element>
    	</xs:sequence>
    	<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
    	<xs:attribute name="version" type="xs:string" use="required"></xs:attribute>
    	<xs:attribute name="jdk" type="xs:string" use="required"></xs:attribute>
    	<xs:attribute name="debug" type="xs:boolean" use="required"></xs:attribute>
    </xs:complexType>


    <xs:complexType name="AssignedIdType">
    	<xs:sequence>
    		<xs:element name="groupId" type="xs:string"></xs:element>
    		<xs:element name="artifactId" type="xs:string"></xs:element>
    		<xs:element name="version" type="xs:string"></xs:element>
    		<xs:element name="name" type="xs:string"></xs:element>
    		<xs:element name="vendor" type="xs:string"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="InspectedIdType">
    	<xs:sequence>
    		<xs:element name="groupIds" maxOccurs="1" minOccurs="0">
    			<xs:complexType>
    				<xs:sequence>
    					<xs:element name="groupId"
    						type="InspectedValuesType" maxOccurs="unbounded" minOccurs="1">
    					</xs:element>
    				</xs:sequence>
    			</xs:complexType>
    		</xs:element>
    		<xs:element name="artifactIds" maxOccurs="1"
    			minOccurs="0">
    			<xs:complexType>
    				<xs:sequence>
    					<xs:element name="artifactId"
    						type="InspectedValuesType" maxOccurs="unbounded" minOccurs="1">
    					</xs:element>
    				</xs:sequence>
    			</xs:complexType>
    		</xs:element>
    		<xs:element name="versions" maxOccurs="1" minOccurs="0">
    			<xs:complexType>
    				<xs:sequence>
    					<xs:element name="version"
    						type="InspectedValuesType" maxOccurs="unbounded" minOccurs="1">
    					</xs:element>
    				</xs:sequence>
    			</xs:complexType>
    		</xs:element>
    		<xs:element name="names" maxOccurs="1" minOccurs="0">
    			<xs:complexType>
    				<xs:sequence>
    					<xs:element name="name"
    						type="InspectedValuesType" maxOccurs="unbounded" minOccurs="1">
    					</xs:element>
    				</xs:sequence>
    			</xs:complexType>
    		</xs:element>
    		<xs:element name="vendors" maxOccurs="1" minOccurs="0">
    			<xs:complexType>
    				<xs:sequence>
    					<xs:element name="vendor"
    						type="InspectedValuesType" maxOccurs="unbounded" minOccurs="1">
    					</xs:element>
    				</xs:sequence>
    			</xs:complexType>
    		</xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="InspectedValuesType">
    	<xs:sequence>
    		<xs:element name="value" type="xs:string"
    			maxOccurs="1" minOccurs="1">
    		</xs:element>
    		<xs:element name="weight" type="xs:int" maxOccurs="1" minOccurs="1"></xs:element>
    		<xs:element name="origin" type="xs:string" maxOccurs="unbounded" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>



</xs:schema>

=== apache/archiva-sandbox/archiva-jarinfo/archiva-jarinfo-lib/src/test/resources/jxr.jar-details.xml
<?xml version="1.0" encoding="UTF-8"?>

<jar-details xmlns="http://archiva.apache.org/JARINFO/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://archiva.apache.org/jarinfo-v1_0_0.xsd">
  <assigned-id>
    <groupId>org.apache.maven</groupId>
    <artifactId>maven-jxr</artifactId>
    <version>2.1</version>
  </assigned-id>
  <filename>jxr.jar</filename>
  <timestamp>2007-12-08 15:28:21 UTC</timestamp>
  <size>45721</size>
  <size-uncompressed>87035</size-uncompressed>
  <hash algorithm="sha-1">f903245e7ca6ce8ea7a2c935325770713b839128</hash>
  <hash algorithm="md5">55cb76979cb203bbe44261d0cafe6f57</hash>
  <sealed>false</sealed>
  <generator>
    <name>archiva-jarinfo</name>
    <version>1.0</version>
    <timestamp>2007-12-11 16:31:43 UTC</timestamp>
  </generator>
  <entries count-dirs="13" count-files="28" count-total="41">
    <dir name="META-INF/" timestamp="2007-04-01 02:18:38 UTC"/>
    <dir name="META-INF/maven/" timestamp="2007-04-01 02:18:38 UTC"/>
    <dir name="META-INF/maven/org.apache.maven/" timestamp="2007-04-01 02:18:38 UTC"/>
    <dir name="META-INF/maven/org.apache.maven/maven-jxr/" timestamp="2007-04-01 02:18:38 UTC"/>
    <dir name="org/" timestamp="2007-04-01 02:18:36 UTC"/>
    <dir name="org/apache/" timestamp="2007-04-01 02:18:36 UTC"/>
    <dir name="org/apache/maven/" timestamp="2007-04-01 02:18:36 UTC"/>
    <dir name="org/apache/maven/jxr/" timestamp="2007-04-01 02:18:36 UTC"/>
    <dir name="org/apache/maven/jxr/ant/" timestamp="2007-04-01 02:18:36 UTC"/>
    <dir name="org/apache/maven/jxr/log/" timestamp="2007-04-01 02:18:36 UTC"/>
    <dir name="org/apache/maven/jxr/pacman/" timestamp="2007-04-01 02:18:36 UTC"/>
    <dir name="org/apache/maven/jxr/util/" timestamp="2007-04-01 02:18:36 UTC"/>
    <dir name="templates/" timestamp="2007-04-01 02:18:36 UTC"/>
    <file name="META-INF/LICENSE.txt" size="11358" timestamp="2007-04-01 02:18:36 UTC">
      <hash algorithm="sha-1">2b8b815229aa8a61e483fb4ba0588b8b6c491890</hash>
    </file>
    <file name="META-INF/MANIFEST.MF" size="124" timestamp="2007-04-01 02:18:36 UTC">
      <hash algorithm="sha-1">dc0807d8d5bf56a003ad17ed47b8168722ac9a2d</hash>
    </file>
    <file name="META-INF/maven/org.apache.maven/maven-jxr/pom.properties" size="114" timestamp="2007-04-01 02:18:38 UTC">
      <hash algorithm="sha-1">1a45d2162d5eef5a0b44f3dc0b8a2ecc930b452c</hash>
    </file>
    <file name="META-INF/maven/org.apache.maven/maven-jxr/pom.xml" size="5275" timestamp="2007-04-01 02:18:02 UTC">
      <hash algorithm="sha-1">7ac183c2eb5ce086b85f752ce569c2538143af53</hash>
    </file>
    <file name="META-INF/NOTICE.txt" size="595" timestamp="2007-04-01 02:18:36 UTC">
      <hash algorithm="sha-1">48c26a2710e48a4a57021b97b61183009c73de13</hash>
    </file>
    <file name="org/apache/maven/jxr/ant/DirectoryScanner.class" size="1012" timestamp="2007-04-01 02:18:36 UTC">
      <hash algorithm="sha-1">53fbd4300bf4c57cc4915a47aad79807867180d1</hash>
    </file>
    <file name="org/apache/maven/jxr/DirectoryIndexer.class" size="8170" timestamp="2007-04-01 02:18:36 UTC">
      <hash algorithm="sha-1">de06d26e463c1104bd00b34c5abe89446160a36c</hash>
    </file>
    <file name="org/apache/maven/jxr/JavaCodeTransform.class" size="19068" timestamp="2007-04-01 02:18:36 UTC">
      <hash algorithm="sha-1">d330d2c96e389455b814ac84292103a53de869d6</hash>
    </file>
    <file name="org/apache/maven/jxr/JXR.class" size="7362" timestamp="2007-04-01 02:18:36 UTC">
      <hash algorithm="sha-1">2f37c069774120f146f43f9252581a6aaa2f14cc</hash>
    </file>
    <file name="org/apache/maven/jxr/JxrException.class" size="475" timestamp="2007-04-01 02:18:36 UTC">
      <hash algorithm="sha-1">e6343ae656004339a4b0f93eee32ef96018a22d8</hash>
    </file>
    <file name="org/apache/maven/jxr/log/Log.class" size="198" timestamp="2007-04-01 02:18:36 UTC">
      <hash algorithm="sha-1">b0c47730748abf0e54de39ddf2cb51435abda1f5</hash>
    </file>
    <file name="org/apache/maven/jxr/log/VelocityLogger.class" size="1677" timestamp="2007-04-01 02:18:36 UTC">
      <hash algorithm="sha-1">9d1854400ba31a3608c3d4c1227adb28e8146302</hash>
    </file>
    <file name="org/apache/maven/jxr/pacman/BaseType.class" size="588" timestamp="2007-04-01 02:18:36 UTC">
      <hash algorithm="sha-1">15e983003d0bec56b677ed42e5f7e729cc077b85</hash>
    </file>
    <file name="org/apache/maven/jxr/pacman/ClassType.class" size="832" timestamp="2007-04-01 02:18:36 UTC">
      <hash algorithm="sha-1">e0a8d0edd209bd5a77c30cdef86d5989aa1d75e3</hash>
    </file>
    <file name="org/apache/maven/jxr/pacman/FileManager.class" size="1639" timestamp="2007-04-01 02:18:36 UTC">
      <hash algorithm="sha-1">8dff6cc13f402e113449a63677223f57e6e2c5c3</hash>
    </file>
    <file name="org/apache/maven/jxr/pacman/ImportType.class" size="1077" timestamp="2007-04-01 02:18:36 UTC">
      <hash algorithm="sha-1">a0d33f0fdbb8b0820977126d07a86004c8b557c8</hash>
    </file>
    <file name="org/apache/maven/jxr/pacman/JavaFile.class" size="2651" timestamp="2007-04-01 02:18:36 UTC">
      <hash algorithm="sha-1">c0f339d0977db7f124c4f80f01f82e79bbe39ef3</hash>
    </file>
    <file name="org/apache/maven/jxr/pacman/JavaFileImpl.class" size="3348" timestamp="2007-04-01 02:18:36 UTC">
      <hash algorithm="sha-1">c5140369f5a85e94026b5462e253fc5f9ec9e899</hash>
    </file>
    <file name="org/apache/maven/jxr/pacman/PackageManager.class" size="4741" timestamp="2007-04-01 02:18:36 UTC">
      <hash algorithm="sha-1">3c095efb71e0881ccc3117fa7268be27f5c53c0e</hash>
    </file>
    <file name="org/apache/maven/jxr/pacman/PackageType.class" size="1306" timestamp="2007-04-01 02:18:36 UTC">
      <hash algorithm="sha-1">c7d5080909c9a5fbb1c198cf57e1521d669af48a</hash>
    </file>
    <file name="org/apache/maven/jxr/util/SimpleWordTokenizer.class" size="2726" timestamp="2007-04-01 02:18:36 UTC">
      <hash algorithm="sha-1">3597a02f5881bd76eb3cffd7017dfbe4a434e837</hash>
    </file>
    <file name="org/apache/maven/jxr/util/StringEntry.class" size="1013" timestamp="2007-04-01 02:18:36 UTC">
      <hash algorithm="sha-1">b903b01111e0a8e01d4ee921ac98169bb357f248</hash>
    </file>
    <file name="templates/allclasses-frame.vm" size="1395" timestamp="2007-04-01 02:18:36 UTC">
      <hash algorithm="sha-1">39e1e72d5aa5c82abba693deb00922b60e71db76</hash>
    </file>
    <file name="templates/index.vm" size="1574" timestamp="2007-04-01 02:18:36 UTC">
      <hash algorithm="sha-1">ad185430042ec9ca8ddd5eb270d34440b1ffeeef</hash>
    </file>
    <file name="templates/overview-frame.vm" size="1462" timestamp="2007-04-01 02:18:36 UTC">
      <hash algorithm="sha-1">783f95bfb2f829507db899251e6c4e70a5b8d021</hash>
    </file>
    <file name="templates/overview-summary.vm" size="2638" timestamp="2007-04-01 02:18:36 UTC">
      <hash algorithm="sha-1">0453fe761cd034ce3553909e70f742fdf1b3a647</hash>
    </file>
    <file name="templates/package-frame.vm" size="1554" timestamp="2007-04-01 02:18:36 UTC">
      <hash algorithm="sha-1">e0c17e48e3753bb866cd6f263b790df4727f02cd</hash>
    </file>
    <file name="templates/package-summary.vm" size="3063" timestamp="2007-04-01 02:18:36 UTC">
      <hash algorithm="sha-1">62b76ceca11f22b13db896a25976cbb8aaafbe54</hash>
    </file>
  </entries>
  <bytecode count-classes="17" count-packages="5">
    <hash algorithm="sha-1">c8f6fa47ac1363498c06b7172ee4a6cea6c04667</hash>
    <jdk>1.1</jdk>
    <debug>true</debug>
    <class name="org.apache.maven.jxr.ant.DirectoryScanner" version="45.3" jdk="1.1" debug="true">
      <hash algorithm="sha-1">53fbd4300bf4c57cc4915a47aad79807867180d1</hash>
      <import>java.io.File</import>
      <import>java.lang.Object</import>
      <import>java.lang.String</import>
      <import>java.lang.StringBuffer</import>
      <import>java.lang.System</import>
      <import>org.apache.maven.jxr.ant.DirectoryScanner</import>
      <import>org.codehaus.plexus.util.DirectoryScanner</import>
      <method>&lt;init&gt;()V</method>
      <method>addDefaultExcludes()V</method>
    </class>
    <class name="org.apache.maven.jxr.DirectoryIndexer" version="45.3" jdk="1.1" debug="true">
      <hash algorithm="sha-1">de06d26e463c1104bd00b34c5abe89446160a36c</hash>
      <import>java.io.File</import>
      <import>java.io.FileWriter</import>
      <import>java.io.OutputStreamWriter</import>
      <import>java.io.Writer</import>
      <import>java.lang.Class</import>
      <import>java.lang.ClassNotFoundException</import>
      <import>java.lang.Exception</import>
      <import>java.lang.NoClassDefFoundError</import>
      <import>java.lang.Object</import>
      <import>java.lang.String</import>
      <import>java.lang.StringBuffer</import>
      <import>java.lang.Throwable</import>
      <import>java.util.Collection</import>
      <import>java.util.Enumeration</import>
      <import>java.util.HashMap</import>
      <import>java.util.Iterator</import>
      <import>java.util.Map</import>
      <import>java.util.TreeMap</import>
      <import>org.apache.maven.jxr.DirectoryIndexer</import>
      <import>org.apache.maven.jxr.JxrException</import>
      <import>org.apache.maven.jxr.log.Log</import>
      <import>org.apache.maven.jxr.pacman.BaseType</import>
      <import>org.apache.maven.jxr.pacman.ClassType</import>
      <import>org.apache.maven.jxr.pacman.PackageManager</import>
      <import>org.apache.maven.jxr.pacman.PackageType</import>
      <import>org.apache.oro.text.perl.Perl5Util</import>
      <import>org.apache.velocity.Template</import>
      <import>org.apache.velocity.VelocityContext</import>
      <import>org.apache.velocity.app.VelocityEngine</import>
      <import>org.apache.velocity.context.AbstractContext</import>
      <import>org.apache.velocity.context.Context</import>
      <import>org.codehaus.plexus.util.IOUtil</import>
      <method>&lt;init&gt;(Lorg/apache/maven/jxr/pacman/PackageManager;Ljava/lang/String;)V</method>
